development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  database: album_management_db
  password: postgres9

  
production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  database: album_management_db
  password: postgres9

test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  username: postgres
  database: test_album_db
  password: postgres9